import fs from "fs/promises";
import { logger } from "../config/logger.js";

export class ParserService {
  /**
   * Parse code files to extract structural metadata, complexity, and basic code smells.
   * @param {Array} fileTree Array of files generated by GitHubService.fetchFileTree.
   */
  async parse(fileTree) {
    try {
      logger.info(`Starting code parsing for ${fileTree.length} files...`);

      const scanSummary = {
        totalFunctions: 0,
        totalClasses: 0,
        complexityAlerts: [], // { file, line, type, message }
        securityAlerts: [], // { file, line, type, message }
        smells: [], // { file, line, type, message }
      };

      // We only parse source code files
      const codeExtensions = /\.(js|jsx|ts|tsx|py|java|go|rb|php|cpp|c|h|cs)$/i;

      // Limit scanning to at most 100 code files to prevent memory/performance issues
      const candidateFiles = fileTree.filter(
        (f) => codeExtensions.test(f.name) && f.size < 200000 // limit to <200KB
      );

      // Sort candidate files to prioritize main folders
      candidateFiles.sort((a, b) => {
        const score = (p) => {
          if (p.includes("src/")) return 1;
          if (p.includes("app/")) return 1;
          if (p.includes("lib/")) return 2;
          if (p.includes("test/") || p.includes("spec/")) return 4;
          return 3;
        };
        return score(a.path) - score(b.path);
      });

      const filesToParse = candidateFiles.slice(0, 75);

      for (const file of filesToParse) {
        try {
          const content = await fs.readFile(file.absolutePath, "utf8");
          const lines = content.split(/\r?\n/);
          
          // Multi-language parsing regexes
          const isJS = /\.(js|jsx|ts|tsx)$/i.test(file.name);
          const isPython = /\.py$/i.test(file.name);

          // 1. Structural regexes
          let classRegex = /class\s+([A-Za-z0-9_]+)/g;
          let funcRegex = /(?:function\s+([A-Za-z0-9_]+)|const\s+([A-Za-z0-9_]+)\s*=\s*(?:\([^)]*\)|[A-Za-z0-9_]+)\s*=>)/g;

          if (isPython) {
            classRegex = /class\s+([A-Za-z0-9_]+)\s*(\(|:)/g;
            funcRegex = /def\s+([A-Za-z0-9_]+)\s*\(/g;
          }

          // Reset regexes
          classRegex.lastIndex = 0;
          funcRegex.lastIndex = 0;

          // Match classes
          const classMatches = content.match(classRegex);
          if (classMatches) {
            scanSummary.totalClasses += classMatches.length;
          }

          // Match functions
          const funcMatches = content.match(funcRegex);
          if (funcMatches) {
            scanSummary.totalFunctions += funcMatches.length;
          }

          // 2. Line-by-line inspection (smells, secrets, nested blocks)
          let currentBrackets = 0;
          let lineCounter = 0;

          for (let i = 0; i < lines.length; i++) {
            const line = lines[i];
            const trimmedLine = line.trim();
            lineCounter++;

            // Track bracket depth (complexity heuristic for JS/C/Java)
            if (isJS) {
              const openBrackets = (trimmedLine.match(/{/g) || []).length;
              const closeBrackets = (trimmedLine.match(/}/g) || []).length;
              currentBrackets += openBrackets - closeBrackets;

              if (currentBrackets > 4) {
                scanSummary.complexityAlerts.push({
                  file: file.path,
                  line: lineCounter,
                  type: "deep-nesting",
                  message: `Deep nesting detected (nesting level: ${currentBrackets})`,
                });
              }
            }

            // Code smells
            if (trimmedLine.includes("console.log")) {
              scanSummary.smells.push({
                file: file.path,
                line: lineCounter,
                type: "console-log",
                message: "Production code smell: console.log statement found",
              });
            }

            if (/TODO|FIXME|HACK/i.test(trimmedLine)) {
              scanSummary.smells.push({
                file: file.path,
                line: lineCounter,
                type: "todo-comment",
                message: `Pending task found: ${trimmedLine}`,
              });
            }

            // Security secrets scanner
            // Looks for key = '...', token: '...', secret = "...", password = "..."
            const secretsPatterns = [
              /(?:api_key|apikey|secret|jwt_secret|private_key|token|auth_token|password|passwd|credentials)\s*[:=]\s*['"`][A-Za-z0-9_\-+=/]{12,}['"`]/i,
              /ghp_[A-Za-z0-9]{36}/, // GitHub token
              /xoxb-[0-9]{11,13}-[0-9]{11,13}-[A-Za-z0-9]{24}/, // Slack token
            ];

            for (const pattern of secretsPatterns) {
              if (pattern.test(trimmedLine)) {
                // Ignore env files and example templates
                if (!file.name.includes(".env") && !file.name.includes("example")) {
                  scanSummary.securityAlerts.push({
                    file: file.path,
                    line: lineCounter,
                    type: "hardcoded-secret",
                    message: "CRITICAL: Hardcoded credentials or API key pattern detected",
                  });
                }
              }
            }
          }

          // Complexity: Large file heuristic
          if (lines.length > 300) {
            scanSummary.complexityAlerts.push({
              file: file.path,
              line: 1,
              type: "large-file",
              message: `File has ${lines.length} lines. Consider splitting into smaller modules.`,
            });
          }
        } catch (err) {
          logger.error(`Error parsing file ${file.path}: ${err.message}`);
        }
      }

      return scanSummary;
    } catch (error) {
      logger.error(`Parser error: ${error.message}`);
      throw error;
    }
  }
}
