import fs from "fs/promises";
import path from "path";
import { logger } from "../config/logger.js";

export class ScannerService {
  /**
   * Scan the extracted repository folder and collect metrics.
   * @param {string} repoPath Absolute path to the extracted repository folder.
   * @param {Array} fileTree Array of files generated by GitHubService.fetchFileTree.
   */
  async scan(repoPath, fileTree) {
    try {
      logger.info(`Starting scanner on repository path: ${repoPath}`);
      
      const metrics = {
        framework: "Unknown",
        language: "Unknown",
        totalFiles: fileTree.length,
        totalLinesOfCode: 0,
        foldersCount: 0,
        dependencies: { production: [], development: [] },
        hasDockerfile: false,
        hasCICD: false,
        hasTests: false,
        testFramework: "Unknown",
        readme: { exists: false, wordCount: 0, sections: [] },
        license: "Unknown",
        configFiles: [],
      };

      // 1. Calculate folder counts and lines of code (limit to text files < 500KB)
      const folderSet = new Set();
      let totalLines = 0;

      for (const file of fileTree) {
        const folderName = path.dirname(file.path);
        if (folderName && folderName !== ".") {
          folderSet.add(folderName);
        }

        // Detect config files
        const fileNameLower = file.name.toLowerCase();
        if (
          [
            "dockerfile",
            "docker-compose.yml",
            "docker-compose.yaml",
            ".gitignore",
            ".env.example",
            "tsconfig.json",
            "jsconfig.json",
            "webpack.config.js",
            "vite.config.js",
            "next.config.js",
            "tailwind.config.js",
          ].includes(fileNameLower) ||
          file.path.startsWith(".github/workflows")
        ) {
          metrics.configFiles.push(file.path);
        }

        if (fileNameLower === "dockerfile") metrics.hasDockerfile = true;
        if (file.path.startsWith(".github/workflows")) metrics.hasCICD = true;

        // Try reading lines for files under 500KB to count LOC
        const isCodeExtension = /\.(js|jsx|ts|tsx|py|java|go|rb|php|cpp|c|h|cs|html|css|sh|yml|yaml|json)$/i.test(file.name);
        if (isCodeExtension && file.size < 500000) {
          try {
            const content = await fs.readFile(file.absolutePath, "utf8");
            const lines = content.split(/\r?\n/).length;
            totalLines += lines;
          } catch {
            // Ignore read errors (e.g. binary disguised with extension)
          }
        }
      }

      metrics.foldersCount = folderSet.size;
      metrics.totalLinesOfCode = totalLines;

      // 2. Language Detection based on files in fileTree
      const extCounts = {};
      fileTree.forEach((f) => {
        const ext = path.extname(f.name).toLowerCase();
        if (ext) {
          extCounts[ext] = (extCounts[ext] || 0) + 1;
        }
      });

      const languageMapping = {
        ".js": "JavaScript",
        ".jsx": "JavaScript (React)",
        ".ts": "TypeScript",
        ".tsx": "TypeScript (React)",
        ".py": "Python",
        ".java": "Java",
        ".go": "Go",
        ".rb": "Ruby",
        ".php": "PHP",
        ".cpp": "C++",
        ".c": "C",
        ".cs": "C#",
        ".html": "HTML",
        ".css": "CSS",
        ".sh": "Shell",
      };

      let primaryExt = null;
      let maxCount = 0;
      Object.entries(extCounts).forEach(([ext, count]) => {
        if (count > maxCount && languageMapping[ext]) {
          maxCount = count;
          primaryExt = ext;
        }
      });

      if (primaryExt) {
        metrics.language = languageMapping[primaryExt];
      }

      // 3. README and License Scan
      const readmeFile = fileTree.find((f) => /^readme\.md$/i.test(f.name));
      if (readmeFile) {
        metrics.readme.exists = true;
        try {
          const readmeContent = await fs.readFile(readmeFile.absolutePath, "utf8");
          metrics.readme.wordCount = readmeContent.split(/\s+/).filter(Boolean).length;

          // Search sections in readme
          const sections = [];
          const headings = readmeContent.match(/^#+\s+(.+)$/gm);
          if (headings) {
            headings.forEach((h) => {
              sections.push(h.replace(/^#+\s+/, "").trim());
            });
          }
          metrics.readme.sections = sections;

          // Check license mention inside README
          if (/license/i.test(readmeContent)) {
            const licenseMatch = readmeContent.match(/mit|apache|gpl|bsd/i);
            if (licenseMatch) {
              metrics.license = licenseMatch[0].toUpperCase();
            }
          }
        } catch (err) {
          logger.error(`Error scanning README: ${err.message}`);
        }
      }

      // Check license file
      const licenseFile = fileTree.find((f) => /^license$/i.test(f.name) || /^license\.txt$/i.test(f.name) || /^license\.md$/i.test(f.name));
      if (licenseFile) {
        try {
          const licenseContent = await fs.readFile(licenseFile.absolutePath, "utf8");
          const match = licenseContent.match(/MIT|Apache|GNU|GPL|BSD/i);
          metrics.license = match ? match[0].toUpperCase() : "Detected (Custom)";
        } catch (err) {
          logger.error(`Error scanning License file: ${err.message}`);
        }
      }

      // 4. Framework and Dependency detection
      const packageJsonFile = fileTree.find((f) => f.name === "package.json");
      if (packageJsonFile) {
        try {
          const pkg = JSON.parse(await fs.readFile(packageJsonFile.absolutePath, "utf8"));
          metrics.dependencies.production = Object.keys(pkg.dependencies || {});
          metrics.dependencies.development = Object.keys(pkg.devDependencies || {});

          // Framework heuristics
          const allDeps = [...metrics.dependencies.production, ...metrics.dependencies.development];
          if (allDeps.includes("next")) {
            metrics.framework = "Next.js";
          } else if (allDeps.includes("react")) {
            metrics.framework = "React";
          } else if (allDeps.includes("express")) {
            metrics.framework = "Express.js";
          } else if (allDeps.includes("vue")) {
            metrics.framework = "Vue";
          } else if (allDeps.includes("@angular/core")) {
            metrics.framework = "Angular";
          } else if (allDeps.includes("nuxt")) {
            metrics.framework = "Nuxt";
          } else if (allDeps.includes("nest")) {
            metrics.framework = "NestJS";
          }

          // Test framework
          if (allDeps.includes("jest")) {
            metrics.hasTests = true;
            metrics.testFramework = "Jest";
          } else if (allDeps.includes("vitest")) {
            metrics.hasTests = true;
            metrics.testFramework = "Vitest";
          } else if (allDeps.includes("mocha")) {
            metrics.hasTests = true;
            metrics.testFramework = "Mocha";
          } else if (allDeps.includes("cypress")) {
            metrics.hasTests = true;
            metrics.testFramework = "Cypress";
          } else if (allDeps.includes("playwright")) {
            metrics.hasTests = true;
            metrics.testFramework = "Playwright";
          }
        } catch (err) {
          logger.error(`Error reading package.json: ${err.message}`);
        }
      }

      // Python frameworks
      const requirementsFile = fileTree.find((f) => f.name === "requirements.txt");
      if (requirementsFile) {
        try {
          const reqs = await fs.readFile(requirementsFile.absolutePath, "utf8");
          if (/django/i.test(reqs)) metrics.framework = "Django";
          else if (/flask/i.test(reqs)) metrics.framework = "Flask";
          else if (/fastapi/i.test(reqs)) metrics.framework = "FastAPI";

          if (/pytest/i.test(reqs)) {
            metrics.hasTests = true;
            metrics.testFramework = "pytest";
          } else if (/unittest/i.test(reqs)) {
            metrics.hasTests = true;
            metrics.testFramework = "unittest";
          }
        } catch (err) {
          logger.error(`Error reading requirements.txt: ${err.message}`);
        }
      }

      return metrics;
    } catch (error) {
      logger.error(`Scanner error: ${error.message}`);
      throw error;
    }
  }
}
